name: Scheduled Vercel Cron Job

on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 15 * * *'  # 매일 오후 3시 UTC (한국 시간으로는 오전 12시)

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel API
        run: |
          curl -X GET "https://growth-tracker-ecru.vercel.app/api/scheduler"