name: Scheduled Vercel Cron Job

on:
  schedule:
    - cron: '* * * * *'  # 매일 오전 5시

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel API
        run: |
          curl -X GET "https://growth-tracker-ecru.vercel.app/api/scheduler?token=${{ secrets.VERCEL_SECRET_TOKEN }}"