name: Call API After Vercel Deploy

on:
  push:
    branches:
      - develop

jobs:
  wait-for-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Vercel Deployment
        id: wait-for-vercel
        run: |
          echo "Waiting for Vercel deployment..."
          while true; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" "https://api.vercel.com/v5/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}")
            status=$(echo $response | jq -r '.deployments[0].state')
            url=$(echo $response | jq -r '.deployments[0].url')
            echo "API Response: $response"
            if [ "$status" = "READY" ]; then
              echo "Deployment is ready!"
              echo "::set-output name=deployment_url::$url"
              break
            else
              echo "Deployment status: $status. Waiting..."
              sleep 10
            fi
          done
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  call-api:
    runs-on: ubuntu-latest
    needs: wait-for-vercel

    steps:
      - name: Call API
        run: |
          echo "Calling your API..."
          curl -X POST https://your-api-endpoint.com/trigger
          echo "Deployment URL: ${{ steps.wait-for-vercel.outputs.deployment_url }}"
