name: Call URL every 

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  call-url:
    runs-on: ubuntu-latest
    steps:
      - name: Call URL
        run: curl -X GET "https://growth-tracker-text.vercel.app/api/notice/cron"
