name: Call URL Daily on Main Branch

on:
  schedule:
    - cron: '*/5 * * * *'  

jobs:
  call-url:
    runs-on: ubuntu-latest
    steps:
      - name: Call specific URL
        run: curl -X GET "https://growth-tracker-ecru.vercel.app/api/vercel-cron"  # 호출하려는 URL로 변경하세요
